version: "3.8"

services:
  django:
    image: django_nginx
    container_name: django_nginx_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - dns
    networks:
      - app_network

  dns:
    image: dns_server
    container_name: dns_server_container
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
